# Generated by Django 3.0.5 on 2021-01-31 10:41

import api.transactions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restraunt', '0002_auto_20210131_1113'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(default=api.transactions.models.generate_trans_id, max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('trans_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('restraunt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restraunt.restraunt')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
