# Generated by Django 3.0.5 on 2021-02-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_userdealsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdealsubscription',
            name='meals_had',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdealsubscription',
            name='meals_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
