# Generated by Django 3.0.5 on 2021-01-31 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='close_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='open_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='restraunt_standards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_meals', models.PositiveIntegerField(default=0)),
                ('value_of_meal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restraunt_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restraunt.restraunt')),
            ],
        ),
    ]
