# Generated by Django 3.0.5 on 2021-02-05 17:59

import api.restraunt.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0002_auto_20210131_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='rest_code',
            field=models.CharField(default=api.restraunt.models.generate_code, max_length=10),
        ),
        migrations.AddField(
            model_name='restraunt_standards',
            name='deal_banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restraunt_standards',
            name='deal_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restraunt_standards',
            name='deal_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restraunt_standards',
            name='restraunt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restraunt.restraunt'),
        ),
    ]
